//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuroAsistan.Resources.ExceptionResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RESOURCES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RESOURCES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuroAsistan.Resources.ExceptionResources.RESOURCES", typeof(RESOURCES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at Ctor of FrmLogin..
        /// </summary>
        internal static string RC_2000 {
            get {
                return ResourceManager.GetString("RC_2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at Login method in FrmLogin..
        /// </summary>
        internal static string RC_2001 {
            get {
                return ResourceManager.GetString("RC_2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at Ctor of FrmPerson..
        /// </summary>
        internal static string RC_2002 {
            get {
                return ResourceManager.GetString("RC_2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at Load method of FrmPerson..
        /// </summary>
        internal static string RC_2003 {
            get {
                return ResourceManager.GetString("RC_2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at Save method of FrmPerson..
        /// </summary>
        internal static string RC_2004 {
            get {
                return ResourceManager.GetString("RC_2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at GetById method of PersonManager..
        /// </summary>
        internal static string RC_2005 {
            get {
                return ResourceManager.GetString("RC_2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at SavePerson method of PersonManager..
        /// </summary>
        internal static string RC_2006 {
            get {
                return ResourceManager.GetString("RC_2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at UpdatePerson method of PersonManager..
        /// </summary>
        internal static string RC_2007 {
            get {
                return ResourceManager.GetString("RC_2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at DeletePerson method of PersonManager..
        /// </summary>
        internal static string RC_2008 {
            get {
                return ResourceManager.GetString("RC_2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at ActivatePerson method of PersonManager..
        /// </summary>
        internal static string RC_2009 {
            get {
                return ResourceManager.GetString("RC_2009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at GetPersonList method of PersonManager..
        /// </summary>
        internal static string RC_2010 {
            get {
                return ResourceManager.GetString("RC_2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at Ctor of FrmPersonList..
        /// </summary>
        internal static string RC_2011 {
            get {
                return ResourceManager.GetString("RC_2011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at Load method of FrmPersonList..
        /// </summary>
        internal static string RC_2012 {
            get {
                return ResourceManager.GetString("RC_2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at AddPerson method of FrmPersonList..
        /// </summary>
        internal static string RC_2013 {
            get {
                return ResourceManager.GetString("RC_2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at UpdatePerson method of FrmPersonList..
        /// </summary>
        internal static string RC_2014 {
            get {
                return ResourceManager.GetString("RC_2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at frm_person_FormClosed method of FrmPersonList..
        /// </summary>
        internal static string RC_2015 {
            get {
                return ResourceManager.GetString("RC_2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at Delete method of FrmPersonList..
        /// </summary>
        internal static string RC_2016 {
            get {
                return ResourceManager.GetString("RC_2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at Activate method of FrmPersonList..
        /// </summary>
        internal static string RC_2017 {
            get {
                return ResourceManager.GetString("RC_2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at Search method of FrmPersonList..
        /// </summary>
        internal static string RC_2018 {
            get {
                return ResourceManager.GetString("RC_2018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at btnRefreshList_Click method of FrmPersonList..
        /// </summary>
        internal static string RC_2019 {
            get {
                return ResourceManager.GetString("RC_2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at GetById method of ProcurationManager..
        /// </summary>
        internal static string RC_2020 {
            get {
                return ResourceManager.GetString("RC_2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at SaveProcuration method of ProcurationManager..
        /// </summary>
        internal static string RC_2021 {
            get {
                return ResourceManager.GetString("RC_2021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at UpdateProcuration method of ProcurationManager..
        /// </summary>
        internal static string RC_2022 {
            get {
                return ResourceManager.GetString("RC_2022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at DeleteProcuration method of ProcurationManager..
        /// </summary>
        internal static string RC_2023 {
            get {
                return ResourceManager.GetString("RC_2023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at ActivateProcuration method of ProcurationManager..
        /// </summary>
        internal static string RC_2024 {
            get {
                return ResourceManager.GetString("RC_2024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at GetProcurationList method of ProcurationManager..
        /// </summary>
        internal static string RC_2025 {
            get {
                return ResourceManager.GetString("RC_2025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at  Ctor of FrmProcurationList..
        /// </summary>
        internal static string RC_2026 {
            get {
                return ResourceManager.GetString("RC_2026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at  Load method of FrmProcurationList..
        /// </summary>
        internal static string RC_2027 {
            get {
                return ResourceManager.GetString("RC_2027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at AddProcuration method of FrmProcurationList..
        /// </summary>
        internal static string RC_2028 {
            get {
                return ResourceManager.GetString("RC_2028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at UpdateProcuration method of FrmProcurationList..
        /// </summary>
        internal static string RC_2029 {
            get {
                return ResourceManager.GetString("RC_2029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at frm_Procuration_FormClosed method of FrmProcurationList..
        /// </summary>
        internal static string RC_2030 {
            get {
                return ResourceManager.GetString("RC_2030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at Delete method of FrmProcurationList..
        /// </summary>
        internal static string RC_2031 {
            get {
                return ResourceManager.GetString("RC_2031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at Activate method of FrmProcurationList..
        /// </summary>
        internal static string RC_2032 {
            get {
                return ResourceManager.GetString("RC_2032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at Search method of FrmProcurationList..
        /// </summary>
        internal static string RC_2033 {
            get {
                return ResourceManager.GetString("RC_2033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at btnRefreshList_Click method of FrmProcurationList..
        /// </summary>
        internal static string RC_2034 {
            get {
                return ResourceManager.GetString("RC_2034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at  method of FrmProcurationList..
        /// </summary>
        internal static string RC_2035 {
            get {
                return ResourceManager.GetString("RC_2035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at Ctor of FrmProcuration..
        /// </summary>
        internal static string RC_2036 {
            get {
                return ResourceManager.GetString("RC_2036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at Load method of FrmProcuration..
        /// </summary>
        internal static string RC_2037 {
            get {
                return ResourceManager.GetString("RC_2037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at Save method of FrmProcuration..
        /// </summary>
        internal static string RC_2038 {
            get {
                return ResourceManager.GetString("RC_2038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at GetPersonByActivation method in PersonManager..
        /// </summary>
        internal static string RC_2039 {
            get {
                return ResourceManager.GetString("RC_2039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at refreshListToolStripMenuItem_Click method of FrmPersonList..
        /// </summary>
        internal static string RC_2040 {
            get {
                return ResourceManager.GetString("RC_2040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception handled at refreshListToolStripMenuItem_Click method of FrmProcurationList..
        /// </summary>
        internal static string RC_2041 {
            get {
                return ResourceManager.GetString("RC_2041", resourceCulture);
            }
        }
    }
}
